server:
    port: 8080

spring:

  main:
    allow-circular-references: true

  application:
    name: framesnap-video

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

    # H2 configuration
    datasource:
      #url: jdbc:h2:mem:lanchonetedb
      url: ${MYSQL_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      #driverClassName: org.h2.Driver
      driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
   # h2:
   #   console:
   #     enabled: true
   #     path: /h2-console
    jpa:
      hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
        show-sql: true
        #database-platform: org.hibernate.dialect.H2Dialect
        database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
      properties:
        hibernate:
          format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true

aws:
  cognito:
    client-id: "41vb4ljgmf4bhb8ogafjdjscst"
    client-secret: "5qhg5sq91d2e68f6s3r13sht5kgar1co1lpd9b1eu01a5avdu9b"
    user-pool-id: "us-east-1_Srf0ZBtbc"
    region: "us-east-1"

  credentials:
    access-key: "ASIA2WJTGM7JZ5RHBKJH"
    secret-key: "GbUWhVptJMlLQtCuyoHkP2Ot8SmA+VbEvOHAxaO+"
    session-token: "IQoJb3JpZ2luX2VjEA0aCXVzLXdlc3QtMiJHMEUCIQCKb4G/SPZFihBNd74+CQRECCgEzOBUZ792K9dmMCTH2QIgWq98wapSNUOKCqkSELVps3BxbhLeccGdKWqoe7ELfxQqsQIIZhAAGgw3MzUwODM2NTMwNzUiDGHYSExcrmvEE+WTJCqOAuKZS4jYFh5rrUKCCEbC4IB9gZyiZRrg8fFFT22uTFruuQQai8p8aPgF2EjL4TZS4dzKrTAb8o5xe3bTeUy5PCcoaxMhn2zhTCg4HmWPcTZQmMKJCXXyshaA/k+CaDFpZZBmfbpjXj4EeECMA6vYJjn9wN7zklHSN/Fw22dxBt9QF/NdSFiLVBPuckyXoKDeoS19tVFbri9jeB3pTb5uZI1lMRg7tnxcuWoaa3dpgQwxRoC+ofGtHscFEEBVQXnanj1ZHb3sTvh9YeEJiMrY1T3KdF98ROMm9YaHPa7y+sC6raYOKaPjw81t/nQPtoPZWihnPDkeJltmVGsizS0837QQlHUNuVY312HVEflN1jCYr+e+BjqdAeSvY9DWoFGB/2IEBvKpS8NDKUxkyVC1BXn9vJrMZfmGlB+az+p5ymw4vnlKC2yCIIL8xu+4JtGEvLkksA9yuHEOF5/hqyCdKBZqK50OOR8LUdw8sHMSywCe/N4qrnld3bLQ9Elj5tCDYzTJ//f5aKIE3ecgNK5JlKI+qrAV5MEQMuuqjwoqiD3lXR/VHRheu4Bc9AiW6aYa70C0EtI="

redis:
  host: "redis-19990.c61.us-east-1-3.ec2.redns.redis-cloud.com"
  port: "19990"
  username: "default"
  password: "RGDMNXE1aPagkFG4fJTlpdK0VoGBXdZl"
  #password: ${REDIS_PASSWORD} # Recomendado usar variável de ambient

sqs:
  queue-url: "https://sqs.us-east-1.amazonaws.com/735083653075/frame-snap-video-queue"


# OpenAPI
springdoc:
  api-docs:
    path: /api-docs

# Swagger
  swagger-ui:
    path: /swagger-ui.html

