server:
    port: 8082

spring:

  main:
    allow-circular-references: true

  application:
    name: framesnap-video

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true

aws:

  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    session-token: ${AWS_SESSION_TOKEN}
    region: ${AWS_REGION}

  s3:
    endpoint: ${S3_ENDPOINT}
    bucket: ${S3_BUCKET}
    region: ${AWS_REGION}

  sqs:
    queue-url: ${SQS_QUEUE_URL}

  dynamodb:
    endpoint: ${DYNAMO_ENDPOINT}
    table-name: ${DYNAMO_TABLE_NAME}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}

logging:
  level:
    com.fiap.framesnap.infrastructure.video: DEBUG

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs

# Swagger
  swagger-ui:
    path: /swagger-ui.html

